### ISSUE TITLE
Could not call custom method

### ISSUE THREAD

**Issue by razorahul** [oogbox/odoo-mobile-api#12]
I have this method in my Python file

```
@api.model
    def get_wallet_balance(self, ID_number):
        wallet_balance = 0.0
        partner = self.env['res.partner'].sudo().search(
            [('member_id_number', '=', ID_number)],limit=1
        )
        if partner:
            wallet_balance = partner.wallet_balance
        print 'wallet_balance========================',wallet_balance
        return wallet_balance
```

Calling method

```
        App context = (App) getApplicationContext();
        OArguments oArguments = new OArguments();
        oArguments.add(user.getUserId());
        final OdooClient client = new OdooClient.Builder(context)
                .setHost(OConstants.URL_ODOO)
                .setSession(user.getSessionId()).build();

        client.call_kw("res.partner", "get_wallet_balance", arguments, response);
```

Error
```
I am getting the following error
E/a: ERROR: 
     **** get_wallet_balance() takes exactly 2 arguments (1 given) ****
     on http://*****/web/dataset/call_kw/res.partner/get_wallet_balance [5946]
I/Choreographer: Skipped 124 frames!  The application may be doing too much work on its main thread.
```

I am able to call other methods which don't have arguments.
Can anyone please mention where I am going wrong?

**Comment by chirag-acespritech** [comment]
pass self as blank list.this should work.
Like
OArguments oArguments = new OArguments();
oArguments.add(Arrays.aslist());
oArguments.add(user.getUserId());

**Comment by razorahul** [comment]
@chirag-acespritech It doesn't work... It gives me the following error.

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.odoo, PID: 28808
                  com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 37 path $.result
                      at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:200)
                      at com.google.gson.Gson.fromJson(Gson.java:810)
                      at com.google.gson.Gson.fromJson(Gson.java:775)
                      at com.google.gson.Gson.fromJson(Gson.java:724)
                      at com.google.gson.Gson.fromJson(Gson.java:696)
                      at oogbox.api.odoo.client.a.onResponse(Unknown Source)
                      at oogbox.api.odoo.client.a.onResponse(Unknown Source)
                      at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65)
                      at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
                   Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 37 path $.result
                      at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:388)
                      at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183)
                      at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
                      at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)

```

**Comment by chirag-acespritech** [comment]
take a look at this 
https://github.com/oogbox/odoo-mobile-api/issues/8#issuecomment-403684787

**Comment by razorahul** [comment]
@chirag-acespritech That is for methods with `@api.multi`. Thanks for the help though.

**Comment by bunny-oogbox** [comment]
Hello @razorahul Sorry for delay reply.

You are calling ``@api.model`` which directly takes arguments. So the way you are calling is perfect.
I have tested in **v10, v11 and v12** but i'm not getting this error as you are getting.

What i have tried **im_search** of res.partner:
```python
@api.model
def im_search(self, name, limit=20):
...
```
```java
OArguments arguments = new OArguments();
arguments.add("Demo");
client.call_kw("res.partner", "im_search", arguments, new IOdooResponse() {
    @Override
    public void onResult(OdooResult result) {
        // Getting result
        // {result=[{im_status=offline, user_id=147.0, id=1356.0, name=Demo Portal User}]}
    }
});
```
Is issue still persist ? If Yes, can you tell me on which odoo version are you working ?

Thanks.

**Comment by bunny-oogbox** [comment]
@razorahul Hope you have got the answer. Feel free to re-open if your issue not resolved.
Thanks.
