### ISSUE TITLE
IndexOutOfBoundsException: Invalid index 0, size is 0 Exception

### ISSUE THREAD

**Issue by chirag-acespritech** [oogbox/odoo-mobile-api#13]
Thanks for awesome Lib.
however i am getting 
java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
        at java.util.ArrayList.get(ArrayList.java:308)
        at oogbox.api.odoo.client.OdooVersion.parse(Unknown Source)
        at oogbox.api.odoo.client.a$2.onResult(Unknown Source)
        at oogbox.api.odoo.client.a.onResponse(Unknown Source)
        at oogbox.api.odoo.client.a.onResponse(Unknown Source)
        at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65)
        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:5292)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
        at dalvik.system.NativeStart.main(Native Method)
very frequently. any help will appreciate. thanks

**Comment by bunny-oogbox** [comment]
Hello @chirag-acespritech 

On which version you are trying to connect and when this error occurs ?

**Comment by chirag-acespritech** [comment]
i am getting this while using odoo v8 and v11.

**Comment by bunny-oogbox** [comment]
@chirag-acespritech  Is it still reproducible? If yes, please re-open the issue. 

Thanks.
