### ISSUE TITLE
NetworkDispatcher.processRequest: Unhandled exception java.lang.RuntimeException: Bad URL 

### ISSUE THREAD

**Issue by prashantpag26** [oogbox/odoo-mobile-api#22]
`client.authenticate("user","pass", "db", loginCallback);`
when i call it will add this line in base url
> /web/webclient/version_info
and my actual url was different

NetworkDispatcher.processRequest: Unhandled exception java.lang.RuntimeException: Bad URL credit.digitrinity.com:8080/web/webclient/version_info
    java.lang.RuntimeException: Bad URL credit.digitrinity.com:8080/web/webclient/version_info
        at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:175)
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
     Caused by: java.net.MalformedURLException: Unknown protocol: credit.digitrinity.com
        at java.net.URL.<init>(URL.java:182)
        at java.net.URL.<init>(URL.java:125)
        at com.android.volley.toolbox.HurlStack.executeRequest(HurlStack.java:87)
        at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:123)
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131) 
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111) 
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

**Comment by bunny-oogbox** [comment]
@prashantpag26 Looks like you using your server URL without the prefix (``http://`` or ``https://``)?
