### ISSUE TITLE
Cloud not Call Customer Method

### ISSUE THREAD

**Issue by koz01** [oogbox/odoo-mobile-api#25]
2019-04-10 11:55:44.960 14638-14638/com.matrix E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.matrix, PID: 14638
    com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 38 path $.result
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
        at com.google.gson.Gson.fromJson(Gson.java:927)
        at com.google.gson.Gson.fromJson(Gson.java:892)
        at com.google.gson.Gson.fromJson(Gson.java:841)
        at com.google.gson.Gson.fromJson(Gson.java:813)
        at oogbox.api.odoo.client.ConnectorClient.onResponse(ConnectorClient.java:534)
        at oogbox.api.odoo.client.ConnectorClient.onResponse(ConnectorClient.java:52)
        at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:90)
        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6518)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 38 path $.result
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.Gson.fromJson(Gson.java:927) 
        at com.google.gson.Gson.fromJson(Gson.java:892) 
        at com.google.gson.Gson.fromJson(Gson.java:841) 
        at com.google.gson.Gson.fromJson(Gson.java:813) 
        at oogbox.api.odoo.client.ConnectorClient.onResponse(ConnectorClient.java:534) 
        at oogbox.api.odoo.client.ConnectorClient.onResponse(ConnectorClient.java:52) 
        at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:90) 
        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102) 
        at android.os.Handler.handleCallback(Handler.java:790) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6518) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
My Android Method
<img width="632" alt="ScreenHunter 954" src="https://user-images.githubusercontent.com/16234060/55853677-24a53f00-5b88-11e9-94f8-278fce5be99c.png">

My py Method
<img width="470" alt="ScreenHunter 955" src="https://user-images.githubusercontent.com/16234060/55853697-456d9480-5b88-11e9-99b9-b00c2aa335dc.png">

**Comment by bunny-oogbox** [comment]
Hello @koz01 
Thanks for reporting this issue. After investigating your issue, we found that your method ``get_default_image()`` returning base64 image string directly, and our library not able to convert that string into ``JSONObject`` at the time of parsing response. We are considering this as improvement and will be fixed in the next version.

But for the issue, there is a quick fix,
Just return base64 image string in a dictionary like in your ``get_default_image()`` method.

```python
return {
    'image': tools.image_resize_image_big(base64.b64encode(image))
}
```

Thanks.

**Comment by koz01** [comment]
Thank You. You can close this ticket.
