### ISSUE TITLE
Background running searchread method below error, What ca i do. 

### ISSUE THREAD

**Issue by yokikathir** [oogbox/odoo-mobile-api#26]
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 3 path $[0]
        at com.google.gson.Gson.fromJson(Gson.java:899)
        at com.google.gson.Gson.fromJson(Gson.java:852)
        at com.google.gson.Gson.fromJson(Gson.java:801)
        at com.google.gson.Gson.fromJson(Gson.java:773)
        at oogbox.api.odoo.client.helper.data.OdooResult.getRecords(Unknown Source:57)
        at com.vvsugar.activity.ReminderService$13.onResult(ReminderService.java:686)
        at oogbox.api.odoo.client.a.onResponse(Unknown Source:226)
        at oogbox.api.odoo.client.a.onResponse(Unknown Source:2)
        at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:90)
        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6753)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 3 path $[0]
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
        at com.google.gson.Gson.fromJson(Gson.java:887)
        at com.google.gson.Gson.fromJson(Gson.java:852) 
        at com.google.gson.Gson.fromJson(Gson.java:801) 
        at com.google.gson.Gson.fromJson(Gson.java:773) 
        at oogbox.api.odoo.client.helper.data.OdooResult.getRecords(Unknown Source:57) 
        at com.vvsugar.activity.ReminderService$13.onResult(ReminderService.java:686) 
        at oogbox.api.odoo.client.a.onResponse(Unknown Source:226) 
        at oogbox.api.odoo.client.a.onResponse(Unknown Source:2) 
        at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:90) 
        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102) 
        at android.os.Handler.handleCallback(Handler.java:790) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6753) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 

 if (null != AmtPref.getInstance().getLastSyncDateTransport() && !AmtPref.getInstance().getLastSyncDateTransport().isEmpty()) {
                ODomain mWeb = new ODomain();
                Log.d("Date", AmtPref.getInstance().getLastSyncDate());
                mWeb.add("write_date", ">=", AmtPref.getInstance().getLastSyncDateTransport());
                OdooFields fields = new OdooFields();
                fields.addAll("name", "address1", "address2", "address3", "pin_code", "mobile_no", "bank_id", "bank_branch_id", "account_no", "old_id", "transporter_code", "pan_no");
                int offset = 0;
                int limit = 100000;
                String sorting = "";
                client.searchRead("transporter.master", mWeb, fields, offset, limit, sorting, new IOdooResponse() {
                    @Override
                    public void onResult(OdooResult result) {
                        OdooRecord[] records = result.getRecords();
                    
                        try {
                            for (OdooRecord record : records) {
                                TransPortDb masterDb = new TransPortDb(record.getString("name"), record.getString("address1"), record.getString("address2"), record.getString("address3"), record.getString("pin_code"), record.getString("mobile_no"), record.getString("bank_id"), record.getString("bank_branch_id"), record.getString("account_no"), record.getString("old_id"), record.getString("transporter_code"), record.getString("pan_no"));
                                masterDb.save();
                            }
                        } finally {
                            //  ActiveAndroid.endTransaction();
                        }
                    }
                });
            }

**Comment by bunny-oogbox** [comment]
Hello @yokikathir 
Can you show me your python code of ``search_read`` method override for model ``transporter.master ``?

**Comment by cviacmob** [comment]
pan_number_search = self.env['transporter.master'].search(
[('pan_no', '=', self.pan_no), ('id', '!=', self.id)]) 
this is the python code

**Comment by cviacmob** [comment]
every time get in this issue please resolve issue..

**Comment by bunny-oogbox** [comment]
We are on it. Will be solved in the upcoming version (v1.0.5).
Thanks.

**Comment by efrenba** [comment]
Hi there,

I'm getting the same error, is there a release date of the correction? I need it.
Thanks.
