### ISSUE TITLE
Error when force fail login

### ISSUE THREAD

**Issue by Nabkar** [oogbox/odoo-mobile-api#3]
Hi! 

I'm having problems when im authenticate a false login on my app. Whn I use a real login al works fine but when use a fake login app crash due to a NumberFormatException. There is the error:

```
 E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: es.tlsi.whalesandroidrnt, PID: 9828
                  java.lang.NumberFormatException: Invalid float: "false"
                      at java.lang.StringToReal.invalidReal(StringToReal.java:63)
                      at java.lang.StringToReal.initialParse(StringToReal.java:94)
                      at java.lang.StringToReal.parseFloat(StringToReal.java:323)
                      at java.lang.Float.parseFloat(Float.java:306)
                      at java.lang.Float.valueOf(Float.java:343)
                      at oogbox.api.odoo.client.helper.data.OdooResult.getFloat(Unknown Source)
                      at oogbox.api.odoo.client.helper.data.OdooResult.getInt(Unknown Source)
                      at oogbox.api.odoo.OdooUser.parse(Unknown Source)
                      at oogbox.api.odoo.client.a$3.onResult(Unknown Source)
                      at oogbox.api.odoo.client.a.onResponse(Unknown Source)
                      at oogbox.api.odoo.client.a.onResponse(Unknown Source)
                      at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65)
                      at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5910)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200) 
```

I've got a Singleton that realize the conection to url called "Conexion" and getCliente() method returns OdooCliente object. And there is the code where I'm getting this issue:

```
conexion.getCliente().authenticate(user, pass, db, new AuthenticateListener() {
					@Override
					public void onLoginSuccess(OdooUser user) {
						...
					}

					@Override
					public void onLoginFail(AuthError error) {
						...
					}
				});
```

I surround this instruction by a try catch but catch never execute.

If authentication fails, why don't executes "onLoginFail()"? I debug the app and when execute "conexion.getCliente().authenticate(user, pass, db, new AuthenticateListener() {};", conexion has values, after that, conexion lost all values and I obtain that it is not instantiated.

You know something about? I really appreciate your help.

**Comment by bunny-oogbox** [comment]
Hello @Nabkar 
On which odoo version you are trying to authenticate ?

**Comment by Nabkar** [comment]
Hi! I'm using Odoo version 8.0

**Comment by bunny-oogbox** [comment]
Hello @Nabkar 
You issue fixed in this commit https://github.com/oogbox/odoo-mobile-api/commit/685e030f87b02c69c0e84694bb6170b6fc57accb and will be available soon on Gradle.

Thanks.

**Comment by bunny-oogbox** [comment]
Hello @Nabkar  
New version released with this fix. https://github.com/oogbox/odoo-mobile-api/releases/tag/v1.0.1

If your problem solve, please close this issue. 

Thanks.

**Comment by bunny-oogbox** [comment]
Feel free to re-open issue if your problem not solved.

Thanks.
