### ISSUE TITLE
I have a below error. what is this issue.?

### ISSUE THREAD

**Issue by cviacmob** [oogbox/odoo-mobile-api#33]
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at oogbox.api.odoo.client.OdooVersion.parse(Unknown Source:50)
        at oogbox.api.odoo.client.a$2.onResult(Unknown Source:2)
        at oogbox.api.odoo.client.a.onResponse(Unknown Source:226)
        at oogbox.api.odoo.client.a.onResponse(Unknown Source:2)
        at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:90)
        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6753)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by bunny-oogbox** [comment]
Hello @cviacmob 
On which odoo version you are trying to connect? 

Is this error raised for the first time when you trying to connect your odoo version?

**Comment by cviacmob** [comment]
com.oogbox.api:odoo:1.0.1 in this version am used

**Comment by bunny-oogbox** [comment]
Hello @cviacmob 
Can you please update odoo API version to ``1.0.4`` and If your problem not resolve than let me know.

What Odoo Version are you trying to connect?

**Comment by cviacmob** [comment]
Odoo version 10.0, so that using com.oogbox.api:odoo:1.0.1
