### ISSUE TITLE
what is the issue.?

### ISSUE THREAD

**Issue by cviacmob** [oogbox/odoo-mobile-api#42]
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 3 path $[0]
        at com.google.gson.Gson.fromJson(Gson.java:899)
        at com.google.gson.Gson.fromJson(Gson.java:852)
        at com.google.gson.Gson.fromJson(Gson.java:801)
        at com.google.gson.Gson.fromJson(Gson.java:773)

**Comment by luvyouso** [comment]
i think u parse JSON wrong, it "{}" not String

**Comment by cviacmob** [comment]
How to resolve this issue.

**Comment by cviacmob** [comment]
this is the error.

06-06 10:50:24.200 12416-12416/com.vvsugar E/Errorexception: canweighments{result=[CMS_03, CMS_04, CMS_04_01_2019_1, CMS_04_01_tab, CMS_04_updated, CMS_29, CMS_29_04, CMS_29_04_2019, CMS_29_trail, CMS_29_trail_tab, CMS_29_up, CMS_Fresh, ZSSO]}
    06-06 10:50:24.205 12416-12416/com.vvsugar E/AndroidRuntime: FATAL EXCEPTION: main
        Process: com.vvsugar, PID: 12416
        com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 3 path $[0]

**Comment by luvyouso** [comment]
pls ping skype: caybangmuathuqn i support you.
